run:
  tests: true

linters-settings:
  funlen:
    lines: 150
    statements: 80

  depguard:
    rules:
      prevent_unmaintained_packages:
        list-mode: lax # allow unless explicitely denied
        files:
          - $all
          - "!$test"
        allow:
          - $gostd
        deny:
          - pkg: io/ioutil
            desc: "replaced by io and os packages since Go 1.16: https://tip.golang.org/doc/go1.16#ioutil"

linters:
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
#    - deadcode inactivated
    - depguard
    - dogsled
    - dupl
    - durationcheck
    - errorlint
    - exhaustive
    -  copyloopvar #exportloopref is deprecated
    - funlen
    - gci
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - gofumpt
    - goheader
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
#    - ifshort inactivated
    - importas
    - ineffassign
    - lll
    - makezero
    - misspell
    - nestif
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
#    - structcheck inactivated
    - stylecheck
    - tagliatelle
    - thelper
    - tparallel
#    - typecheck inactivated
    - unconvert
    - unparam
    - unused
#    - varcheck inactivated
    - wastedassign
    - whitespace