name: Task manager ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.23.4'
      - uses: actions/checkout@v4
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.63.4

  #  lint:
  #    runs-on: ubuntu-latest
  #    steps:
  #      - name: Extract branch name
  #        run: echo "BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
  #
  #      - name: Set up Go
  #        uses: actions/setup-go@v3
  #        with:
  #          go-version: ~1.19
  #
  #      - name: Check out code
  #        uses: actions/checkout@v3
  #
  #      - name: Linters
  #        uses: golangci/golangci-lint-action@v3
  #        with:
  #          version: v1.53.3
  #          working-directory: ${{ env.BRANCH }}

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.4'
      - name: Run Unit Tests
        run: go test -race -count 100 -v -tags=unit ./...

#  tests:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Extract branch name
#        run: echo "BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
#
#      - name: Set up Go
#        uses: actions/setup-go@v3
#        with:
#          go-version: '1.23.4'
#
#      - name: Check out code
#        uses: actions/checkout@v3
#
#      - name: Unit tests
#        run: go test -v -count=1 -race -timeout=1m ./...
#        working-directory: ${{ env.BRANCH }}

  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.4'
      - name: Run Integration Tests
        run: go test -v -tags=integration ./...

#  lint:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4
#      - name: Run golangci-lint
#        uses: golangci/golangci-lint-action@v3

  build:
    needs: [unit-tests, integration-tests, lint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.4'
      - name: Build Binary
        run: go build -o cmd/task_manager.go
